### ISSUE TITLE
Share App seems to disappear on contact record

### ISSUE THREAD

**Issue by tylereiland** [DiscipleTools/disciple-tools-share-app#1]
I've been attempting to use the share app with disciples but it seems to randomly disappear on the contact record. One moment I'm logged in and it shows on the contact record but then another time, it doesn't show up for me to find the QR code to share with disciples to track sharing. Just curious if others have noticed similar issue. I've had to uninstall/reinstall multiple times and that fixes things temporarily but then eventually, it disappears again even though it shows active in my plugging.

**Comment by corsacca** [comment]
Hey, 
I expect this commit in v1.25 of Disciple.Tools will address this issue.
https://github.com/DiscipleTools/disciple-tools-theme/commit/4eeb7233e06d3f31186b6d92b8fe96c9e18b98b8
We are pushing out the new version and i'd love to know if this fixes the issue.

**Comment by corsacca** [comment]
I'll consider this issue fixed.
@tylereiland please let us know if you see the issue again.
